# common
spring:
  application:
    name: petclinic
  config:
    import: optional:file:.${SPRING_PROFILES_ACTIVE:dev}.env[.properties]  # 환경별 .env 파일 자동 선택
  profiles:
    default: dev  # 기본 프로파일
  jpa:
    hibernate:
      ddl-auto: none  # MyBatis 사용 시 JPA 미사용 또는 참고용
    open-in-view: false
  messages:
    basename: messages/messages
  sql:
    init:
      mode: always  # schema.sql, data.sql 실행

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: dev.spring.petclinic
  configuration:
    map-underscore-to-camel-case: true
