CREATE DATABASE IF NOT EXISTS jmclinic;

ALTER DATABASE jmclinic
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'jmclinic'@'%' IDENTIFIED BY 'jmclinic';

GRANT ALL PRIVILEGES ON jmclinic.* TO 'jmclinic'@'%';

FLUSH PRIVILEGES;
